[menu] Added a new filter for enabling the advanced CPT-related menu …
Freemius/wordpress-sdk pull request #779
Opened 2024-12-29 08:51 UTC by fajardoleo

…logic.

2025-01-08 16:05 UTC, DanieleAlessandra requested changes
Please take a look to my comments

2025-01-08 16:05 UTC, DanieleAlessandra commented on includes/managers/class-fs-admin-menu-manager.php
> +				$parent_slug = 'admin.php';
Why do we need to re-define `$parent_slug` here? it has just been defined on line 703.

2025-01-08 16:05 UTC, DanieleAlessandra commented on includes/managers/class-fs-admin-menu-manager.php
> +			if ( fs_apply_filter( $this->_module_unique_affix, 'enable_cpt_advanced_menu_logic', false ) ) {
Do we have documentation about `enable_cpt_advanced_menu_logic` hook somewhere?

2025-01-08 16:14 UTC, fajardoleo commented on includes/managers/class-fs-admin-menu-manager.php
> +				$parent_slug = 'admin.php';
@DanieleAlessandra The line above preserves the original behavior when the new filter is not used. When the filter is applied, the behavior changes slightly, and not using `admin.php` may lead to unexpected issues.

2025-01-08 16:15 UTC, fajardoleo commented on includes/managers/class-fs-admin-menu-manager.php
> +			if ( fs_apply_filter( $this->_module_unique_affix, 'enable_cpt_advanced_menu_logic', false ) ) {
@DanieleAlessandra This will be documented. Thanks!

2025-01-08 16:18 UTC, DanieleAlessandra approved these changes
Looks good to me.

2025-01-13 06:30 UTC, swashata approved these changes
LGTM 👏

2025-01-13 06:41 UTC, merged